[project]
name = "iqmpc"
version = "0.1.0"
description = "Pixi conversion of the original iqmpc environment.yaml"
channels = ["nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]
channel-priority = "disabled"

[dependencies]
# CUDA / 系统库
cuda = { version = "*", channel = "nvidia" }
glew = "2.1.0"
glib = "*"

# Python 本身
python = "3.12.*"
pip = "21.0.*"
setuptools = "*"

# PyTorch 生态
pytorch = { version = "<2.5.0", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
pytorch-cuda = { version = "*", channel = "pytorch" }

# 其余 conda-forge 能直接装到的包
numpy = "*"
pandas = "*"
opencv = {version = "*", channel = "conda-forge"}
open3d = "*"
mujoco-python = "*"
gymnasium = ">=1.2,<2.0"
imageio = "2.33.1"
imageio-ffmpeg = "0.4.9"
moviepy = "1.0.3"
protobuf = "*"
pillow = "*"
glfw = "*"
ffmpeg-python = "*"
trimesh = "4.0.9"
tqdm = "*"
wandb = "*"
termcolor = "2.4.0"
absl-py = "2.0.0"
cython = "*"
dm-control = "1.0.*"
hydra-core = "1.3.2"
hydra-submitit-launcher = "1.2.0"
kornia = "*"
omegaconf = "*"
pyquaternion = "0.9.9"
patchelf = "0.17.*"
transforms3d = "0.4.1"
libxml2 = ">=2.13.8,<3"
libxslt = ">=1.1.43,<2"

[pypi-dependencies]
torchrl = "==0.5.*"
tensordict = "==0.5.*"
sapien = "==3.0.1"
